package:
  name: matplotlib
  version: 2.0.2

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 1
  script: python -m pip install "matplotlib==2.0.2"

requirements:
  build:
    - python 2.7*
    - cycler
    - functools32
    - mkl 2017.0.1
    - numpy 1.11*
    - pyparsing >=1.5.6,!=2.0.4,!=2.1.2
    - python-dateutil
    - pytz

  run:
    - python 2.7*
    - cycler
    - functools32
    - mkl 2017.0.1
    - numpy 1.11*
    - pyparsing >=1.5.6,!=2.0.4,!=2.1.2
    - python-dateutil
    - pytz
