package:
  name: wheezy.routing
  version: 0.1.157

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 0
  script: python -m pip install "wheezy.routing==0.1.157"

requirements:
  build:
    - python 2.7*

  run:
    - python 2.7*

test:
  imports:
    - wheezy.routing
